### ISSUE TITLE
Scripts and styles are loaded globally

### ISSUE THREAD

**Issue by robneu** [Seravo/wp-multisite-plugin-statistics#1]
There's no check to see which page is being viewed before loading the plugin scripts and styles. This ends up loading them on all admin pages including pages within the network sites themselves.

The end result of this is slower load times for those pages and broken table headers due to the text being the same color as the background.

**Comment by ottok** [comment]
Thanks for noting!

Would you like to make a pull request about the fix? If you do, I promise to review it quickly and publish a new version of this plugin.

**Comment by robneu** [comment]
Sure, I can do that!

**Comment by ottok** [comment]
Fixed in https://github.com/Seravo/wp-multisite-plugin-statistics/commit/511d839222a99de940a92d8d96b502e9b4750404
